name: Publish release and tag repo

on:
  push:
    branches: 'main'
    paths: 'xword_dl/version'

jobs:
  publish-release-and-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: python -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@f5622bde02b04381239da3573277701ceca8f6a0
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
      - name: Get version
        id: get_version
        run: echo "tagname=$(echo -n v; cat xword_dl/version)" >> $GITHUB_OUTPUT
      - name: Tag repository
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ steps.get_version.outputs.tagname }} 
